branches:
 only:
  - master
  - develop

language: c

os:
 - linux

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.4.0"

before_install:
 - sudo apt-get install -qq mono-devel
 
script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release