language: c

os:
 - linux

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.2.7"

before_install:
 - sudo apt-get install cmake mono-devel mono-gmcs
 
script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release