branches:
 only:
  - develop
  - master

git:
 depth: 1

language: c

env:
 global:
  - EnableNuGetPackageRestore=true

before_install:
 - add-apt-repository "deb http://download.mono-project.com/repo/debian wheezy main"
 - apt-get update
 - apt-get install mono-complete

before_script:
 - chmod +x .ci/nunit.sh

script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release src/AcspNet.sln
 - .ci/nunit.sh .ci/tests.nunit
