branches:
 only:
  - master
  - develop

git:
 depth: 1
  
language: c

os:
 - linux

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.4.0"

before_install:
 - wget " http://tenet.dl.sourceforge.net/project/mono.mirror/Mono%203.4.0/MonoFramework-MDK-3.4.0.macos10.xamarin.x86.pkg"       
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
 
script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release AcspNet.sln
