version: '{build}'

image: Visual Studio 2017

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
- cmd: '"src/.nuget/NuGet.exe" restore src/Simplify.Web.sln'

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
